version: "3"

services:

    shopware:
      image: dockware/dev:6.5.6.1
      container_name: stocknotification_shopware
      ports:
         - "80:80"
         - "3306:3306"
         - "22:22"
         - "8888:8888"
         - "9999:9999"
         - "9998:9998"
      networks:
         - web
      environment:
         - XDEBUG_ENABLED=1
      volumes:
        - "db_volume_stocknotification:/var/lib/mysql"
        - "shop_volume_stocknotification:/var/www/html"
        - "./src/custom/plugins/StockChangeNotificationPlugin:/var/www/html/custom/plugins/StockChangeNotificationPlugin"
    mail:
      container_name: stocknotification_mailhog
      image: mailhog/mailhog
      logging:
        driver: 'none'
      ports:
        - 8025:8025 #web interface
      networks:
        - web

networks:
  web:
    external: false

volumes:
  db_volume_stocknotification:
    driver: local
  shop_volume_stocknotification:
    driver: local