version: "3"

services:

    shopware:
      build:
        context: ./
        dockerfile: ./src/docker/web/Dockerfile
      container_name: shopware
      ports:
         - "80:80"
         - "3306:3306"
         - "22:22"
         - "8888:8888"
         - "9999:9999"
         - "9998:9998"
      networks:
         - web
      environment:
         - XDEBUG_ENABLED=1
      volumes:
        - ./src/bin:/var/www/html/bin
        - ./src/config:/var/www/html/config
        - ./src/custom:/var/www/html/custom
        - ./src/composer.json:/var/www/html/composer.json
        - ./src/.env:/var/www/html/.env
        - ./src/docker/web/php-ini-smtp-dev.ini:/etc/php/8.1/cli/conf.d/php-ini-smtp-dev.ini:ro
        - ./src/docker/web/php-ini-smtp-dev.ini:/etc/php/8.1/fpm/conf.d/php-ini-smtp-dev.ini:ro
        - ./src/docker/web/php-ini-mem-limits.ini:/etc/php/8.1/cli/conf.d/php-ini-mem-limits.ini:ro
        - ./src/docker/web/php-ini-mem-limits.ini:/etc/php/8.1/fpm/conf.d/php-ini-mem-limits.ini:ro
    mail:
      container_name: dockware_mailhog
      image: mailhog/mailhog
      logging:
        driver: 'none'
      ports:
        - 8025:8025 #web interface
      networks:
        - web

networks:
  web:
    external: false