version: "3"

services:

    shopware:
      image: frameworkspl/dockware_nosource:latest
      container_name: shopware
      ports:
         - "80:80"
         - "3306:3306"
         - "22:22"
         - "8888:8888"
         - "9999:9999"
         - "9998:9998"
      networks:
         - web
      environment:
         - XDEBUG_ENABLED=1
      volumes:
        - ./src:/var/www/html

networks:
  web:
    external: false